/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as NewMatchRouteImport } from './routes/new-match'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as FifaIndexRouteImport } from './routes/fifa/index'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments/$tournamentId'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as StatsPlayerIdRouteImport } from './routes/stats/$playerId'
import { Route as ScorecardMatchIdRouteImport } from './routes/scorecard.$matchId'
import { Route as FifaPlayersIndexRouteImport } from './routes/fifa/players/index'
import { Route as FifaMatchesIndexRouteImport } from './routes/fifa/matches/index'
import { Route as FifaPlayersPlayerIdRouteImport } from './routes/fifa/players/$playerId'
import { Route as FifaMatchesNewRouteImport } from './routes/fifa/matches/new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMatchRoute = NewMatchRouteImport.update({
  id: '/new-match',
  path: '/new-match',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaIndexRoute = FifaIndexRouteImport.update({
  id: '/fifa/',
  path: '/fifa/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/tournaments/$tournamentId',
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPlayerIdRoute = StatsPlayerIdRouteImport.update({
  id: '/stats/$playerId',
  path: '/stats/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardMatchIdRoute = ScorecardMatchIdRouteImport.update({
  id: '/scorecard/$matchId',
  path: '/scorecard/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaPlayersIndexRoute = FifaPlayersIndexRouteImport.update({
  id: '/fifa/players/',
  path: '/fifa/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaMatchesIndexRoute = FifaMatchesIndexRouteImport.update({
  id: '/fifa/matches/',
  path: '/fifa/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaPlayersPlayerIdRoute = FifaPlayersPlayerIdRouteImport.update({
  id: '/fifa/players/$playerId',
  path: '/fifa/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaMatchesNewRoute = FifaMatchesNewRouteImport.update({
  id: '/fifa/matches/new',
  path: '/fifa/matches/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-match': typeof NewMatchRoute
  '/records': typeof RecordsRoute
  '/scoring': typeof ScoringRoute
  '/settings': typeof SettingsRoute
  '/scorecard/$matchId': typeof ScorecardMatchIdRoute
  '/stats/$playerId': typeof StatsPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/fifa/': typeof FifaIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/fifa/matches/new': typeof FifaMatchesNewRoute
  '/fifa/players/$playerId': typeof FifaPlayersPlayerIdRoute
  '/fifa/matches/': typeof FifaMatchesIndexRoute
  '/fifa/players/': typeof FifaPlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-match': typeof NewMatchRoute
  '/records': typeof RecordsRoute
  '/scoring': typeof ScoringRoute
  '/settings': typeof SettingsRoute
  '/scorecard/$matchId': typeof ScorecardMatchIdRoute
  '/stats/$playerId': typeof StatsPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/fifa': typeof FifaIndexRoute
  '/stats': typeof StatsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/fifa/matches/new': typeof FifaMatchesNewRoute
  '/fifa/players/$playerId': typeof FifaPlayersPlayerIdRoute
  '/fifa/matches': typeof FifaMatchesIndexRoute
  '/fifa/players': typeof FifaPlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-match': typeof NewMatchRoute
  '/records': typeof RecordsRoute
  '/scoring': typeof ScoringRoute
  '/settings': typeof SettingsRoute
  '/scorecard/$matchId': typeof ScorecardMatchIdRoute
  '/stats/$playerId': typeof StatsPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/fifa/': typeof FifaIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/fifa/matches/new': typeof FifaMatchesNewRoute
  '/fifa/players/$playerId': typeof FifaPlayersPlayerIdRoute
  '/fifa/matches/': typeof FifaMatchesIndexRoute
  '/fifa/players/': typeof FifaPlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/new-match'
    | '/records'
    | '/scoring'
    | '/settings'
    | '/scorecard/$matchId'
    | '/stats/$playerId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/fifa/'
    | '/stats/'
    | '/teams/'
    | '/tournaments/'
    | '/fifa/matches/new'
    | '/fifa/players/$playerId'
    | '/fifa/matches/'
    | '/fifa/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/new-match'
    | '/records'
    | '/scoring'
    | '/settings'
    | '/scorecard/$matchId'
    | '/stats/$playerId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/fifa'
    | '/stats'
    | '/teams'
    | '/tournaments'
    | '/fifa/matches/new'
    | '/fifa/players/$playerId'
    | '/fifa/matches'
    | '/fifa/players'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/new-match'
    | '/records'
    | '/scoring'
    | '/settings'
    | '/scorecard/$matchId'
    | '/stats/$playerId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/fifa/'
    | '/stats/'
    | '/teams/'
    | '/tournaments/'
    | '/fifa/matches/new'
    | '/fifa/players/$playerId'
    | '/fifa/matches/'
    | '/fifa/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  NewMatchRoute: typeof NewMatchRoute
  RecordsRoute: typeof RecordsRoute
  ScoringRoute: typeof ScoringRoute
  SettingsRoute: typeof SettingsRoute
  ScorecardMatchIdRoute: typeof ScorecardMatchIdRoute
  StatsPlayerIdRoute: typeof StatsPlayerIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
  FifaIndexRoute: typeof FifaIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  FifaMatchesNewRoute: typeof FifaMatchesNewRoute
  FifaPlayersPlayerIdRoute: typeof FifaPlayersPlayerIdRoute
  FifaMatchesIndexRoute: typeof FifaMatchesIndexRoute
  FifaPlayersIndexRoute: typeof FifaPlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-match': {
      id: '/new-match'
      path: '/new-match'
      fullPath: '/new-match'
      preLoaderRoute: typeof NewMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa/': {
      id: '/fifa/'
      path: '/fifa'
      fullPath: '/fifa/'
      preLoaderRoute: typeof FifaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$playerId': {
      id: '/stats/$playerId'
      path: '/stats/$playerId'
      fullPath: '/stats/$playerId'
      preLoaderRoute: typeof StatsPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecard/$matchId': {
      id: '/scorecard/$matchId'
      path: '/scorecard/$matchId'
      fullPath: '/scorecard/$matchId'
      preLoaderRoute: typeof ScorecardMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa/players/': {
      id: '/fifa/players/'
      path: '/fifa/players'
      fullPath: '/fifa/players/'
      preLoaderRoute: typeof FifaPlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa/matches/': {
      id: '/fifa/matches/'
      path: '/fifa/matches'
      fullPath: '/fifa/matches/'
      preLoaderRoute: typeof FifaMatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa/players/$playerId': {
      id: '/fifa/players/$playerId'
      path: '/fifa/players/$playerId'
      fullPath: '/fifa/players/$playerId'
      preLoaderRoute: typeof FifaPlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa/matches/new': {
      id: '/fifa/matches/new'
      path: '/fifa/matches/new'
      fullPath: '/fifa/matches/new'
      preLoaderRoute: typeof FifaMatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  NewMatchRoute: NewMatchRoute,
  RecordsRoute: RecordsRoute,
  ScoringRoute: ScoringRoute,
  SettingsRoute: SettingsRoute,
  ScorecardMatchIdRoute: ScorecardMatchIdRoute,
  StatsPlayerIdRoute: StatsPlayerIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
  FifaIndexRoute: FifaIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  FifaMatchesNewRoute: FifaMatchesNewRoute,
  FifaPlayersPlayerIdRoute: FifaPlayersPlayerIdRoute,
  FifaMatchesIndexRoute: FifaMatchesIndexRoute,
  FifaPlayersIndexRoute: FifaPlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
